ls:
    # Regla universal: Carpetas en kebab-case y archivos base en kebab-case
    src/**:
        .dir: kebab-case
        .ts: kebab-case

    # Capa Domain
    "src/**/dtos/**":
        .dto.ts: kebab-case
    "src/**/entities/**":
        .entity.ts: kebab-case
    "src/**/interfaces/**":
        .interface.ts: kebab-case
    "src/**/repositories/**":
        .repository.ts: kebab-case
    "src/**/datasources/**":
        .datasource.ts: kebab-case
    "src/**/models/**":
        .model.ts: kebab-case
    "src/**/errors/**":
        .error.ts: kebab-case

    # Capa Infrastructure
    "src/**/mappers/**":
        .mapper.ts: kebab-case
    "src/**/infrastructure/**/datasources/**":
        .datasource.impl.ts: kebab-case
    "src/**/infrastructure/**/repositories/**":
        .repository.impl.ts: kebab-case

    # Capa Application (Casos de uso)
    "src/**/use-cases/**":
        .use-case.ts: kebab-case

    # Capa Presentation
    "src/**/controllers/**":
        .controller.ts: kebab-case
    "src/**/workers/**":
        .worker.ts: kebab-case
    "src/**/presentation/**":
        .controller.ts: kebab-case
        .router.ts: kebab-case
        .worker.ts: kebab-case

    # Archivos de la capa general o sin subcarpetas concretas
    "src/**/config/**":
        .ts: kebab-case

ignore:
    - node_modules
    - .git
    - dist
    - docs
    - .vscode
    - scripts
    - .agents
    - src/**/index.ts
    - src/**/__tests__
    - src/**/__test__
