ls:
    # Reglas base para toda la carpeta src (Recomendado)
    src/**:
        .dir: kebab-case
        .ts: camelCase | PascalCase

    # Aplica a: src/app/admin-desk/contracts/domain, src/app/shared/identity/domain, etc.
    src/**/domain/**:
        .dto.ts: PascalCase
        .model.ts: PascalCase
        .projection.ts: PascalCase
        .interface.ts: PascalCase
        .datasource.ts: camelCase
        .repository.ts: camelCase

    # Aplica a: src/app/class-track/attendance/infrastructure, etc.
    src/**/infrastructure/**:
        .interface.ts: PascalCase
        .datasource.impl.ts: camelCase
        .mapper.ts: camelCase

    # Aplica a: src/app/admin-desk/payments/application, etc.
    src/**/application/**:
        .use-case.ts: camelCase

    # Aplica a: src/app/class-track/lessons/presentation, etc.
    src/**/presentation/**:
        .controller.ts: PascalCase
        .worker.ts: PascalCase
        .routes.ts: camelCase

    # Reglas específicas para tu carpeta data/ en la raíz
    src/data/config/**:
        .ts: camelCase | PascalCase

    src/data/models/**:
        .model.ts: PascalCase
ignore:
    - node_modules
    - .git
    - dist
    - docs
    - .vscode
    - scripts
    - .agents
    - src/**/__tests__
    - src/**/__test__
