[test]
# Ignorar archivos de configuración, modelos de BD y routers en el reporte de cobertura
coverageIgnore = [
  "src/data/models/**/*.ts", 
  "src/core/config/**/*.ts", 
  "**/*/router.ts",
  "**/*/*.model.ts"  
]
coverageThreshold = 0.8