[test]
coverageThreshold = 0.8

# Ignorar archivos
coveragePathIgnorePatterns = [
  "**/*.test.ts",
  "**/*.spec.ts",
  "**/__tests__/**",

  "src/data/models/**",
  "**/*.model.ts",

  "src/core/config/**"  
]