name: gestion-academica-api-dev
services:
  # Backend
  gestion-academica-api-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    container_name: gestion-academica-api-dev
    restart: always
    tty: true
    stdin_open: true
    environment:
      - FORCE_COLOR=1
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres-db-dev

  # Base de Datos
  postgres-db-dev:
    image: postgres:17
    restart: always
    container_name: postgres-db-dev
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  # Base de Datos
  postgres-dev-data:
