name: gestion-academica-api-test
services:
  # Base de Datos Testing
  postgres-db-test:
    image: postgres:17
    restart: always
    container_name: postgres-db-test
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres-test-data:        # Volumen exclusivo para que las pruebas no rompan la BD principal