# ==========================================
# Etapa 1: Instalador de Dependencias (Node.js)
# ==========================================
FROM node:22-alpine AS prod-deps
WORKDIR /app

# Activamos corepack para usar pnpm de forma nativa
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copiamos ÚNICAMENTE los manifiestos de dependencias
# Reemplazamos bun.lock por pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Instalamos solo dependencias de producción, congeladas y omitiendo scripts inseguros
RUN pnpm install --prod --frozen-lockfile --ignore-scripts


# ==========================================
# Etapa 2: Ejecución a máxima velocidad (Bun)
# ==========================================
FROM oven/bun:1-alpine AS production
WORKDIR /app

# Declaramos explícitamente el entorno de producción
ENV NODE_ENV=production

# Copiamos la carpeta node_modules ya limpia y purificada desde la Etapa 1
COPY --from=prod-deps /app/node_modules ./node_modules

# Copiamos el resto del código fuente del backend
COPY . .

# Exponemos el puerto basado en tus variables
EXPOSE 4000

# Usamos tu script oficial de arranque
CMD ["bun", "run", "start"]