name: gestion-academica-api-dev

services:

  # Base de Datos
  postgres-db-dev:
    image: postgres:17
    restart: always
    container_name: postgres-db-dev
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  # Base de Datos
  postgres-dev-data:
