name: gestion-academica-api-test
services:
  # Backend Testing
  gestion-academica-api-test:
    build:
      context: .
      target: testing
      dockerfile: Dockerfile
    container_name: gestion-academica-api-test
    restart: "no"
    tty: true
    stdin_open: true
    environment:
      - FORCE_COLOR=1
    env_file:
      - .env.test
    ports:
      - "3001:3000"
    depends_on:
      - postgres-db-test

  # Base de Datos Testing
  postgres-db-test:
    image: postgres:17
    restart: always
    container_name: postgres-db-test
    env_file:
      - .env.test            # Postgres usa las credenciales de testing
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres-test-data:        # Volumen exclusivo para que las pruebas no rompan la BD principal